### ISSUE TITLE
Distributed training on a subset of GPU does not work 

### ISSUE THREAD

**Issue by lulmer** [pytorch/torchtune#1103]
I am testing the distributed LoRA training config for llama-3-8B. I have a node with several GPUs but I struggle to train only on a subset of the devices (GPU 0 and 1 are used for something else). 

```shell 
CUDA_VISIBLE_DEVICE=2,3,4,5,6,7 tune  run --nproc_per_node 6 lora_finetune_distributed --config llama3/8B_lora.yaml
```

Here is the full error log : 

```shell
Running with torchrun...
W0620 16:45:12.371000 139746200525888 torch/distributed/run.py:757] 
W0620 16:45:12.371000 139746200525888 torch/distributed/run.py:757] *****************************************
W0620 16:45:12.371000 139746200525888 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0620 16:45:12.371000 139746200525888 torch/distributed/run.py:757] *****************************************
INFO:torchtune.utils.logging:Running LoRAFinetuneRecipeDistributed with resolved config:

batch_size: 2
checkpointer:
  _component_: torchtune.utils.FullModelMetaCheckpointer
  checkpoint_dir: /data/checkpoints/llama-3-8b-instruct-hf/original/
  checkpoint_files:
  - consolidated.00.pth
  model_type: LLAMA3
  output_dir: /tmp/Meta-Llama-3-8B-Instruct/
  recipe_checkpoint: null
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
device: cuda
dtype: bf16
enable_activation_checkpointing: false
epochs: 1
gradient_accumulation_steps: 32
log_every_n_steps: 1
log_peak_memory_stats: false
loss:
  _component_: torch.nn.CrossEntropyLoss
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
max_steps_per_epoch: null
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: /tmp/lora_finetune_output
model:
  _component_: torchtune.models.llama3.lora_llama3_8b
  apply_lora_to_mlp: false
  apply_lora_to_output: false
  lora_alpha: 16
  lora_attn_modules:
  - q_proj
  - v_proj
  lora_rank: 8
optimizer:
  _component_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: 0.01
output_dir: /tmp/lora_finetune_output
resume_from_checkpoint: false
seed: null
shuffle: true
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /data/checkpoints/llama-3-8b-instruct-hf/original/tokenizer.model

[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspaces/torchtune/recipes/lora_finetune_distributed.py", line 684, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/workspaces/torchtune/torchtune/config/_parse.py", line 50, in wrapper
[rank0]:     sys.exit(recipe_main(conf))
[rank0]:              ^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspaces/torchtune/recipes/lora_finetune_distributed.py", line 677, in recipe_main
[rank0]:     recipe = LoRAFinetuneRecipeDistributed(cfg=cfg)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspaces/torchtune/recipes/lora_finetune_distributed.py", line 132, in __init__
[rank0]:     self.seed = utils.set_seed(seed=cfg.seed)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspaces/torchtune/torchtune/utils/seed.py", line 53, in set_seed
[rank0]:     seed = _broadcast_tensor(rand_seed, 0).item()  # sync seed across ranks
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/workspaces/torchtune/torchtune/utils/_distributed.py", line 113, in _broadcast_tensor
[rank0]:     dist.broadcast(tensor, src=src, group=None)
[rank0]:   File "/home/vscode/py-env/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/vscode/py-env/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2136, in broadcast
[rank0]:     work = default_pg.broadcast([tensor], opts)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1866, internal error - please report this issue to the NCCL developers, NCCL version 2.20.5
[rank0]: ncclInternalError: Internal check failed.
[rank0]: Last error:
[rank0]: Bootstrap : no socket interface found
W0620 16:45:22.378000 139746200525888 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 60944 closing signal SIGTERM
W0620 16:45:22.378000 139746200525888 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 60945 closing signal SIGTERM
W0620 16:45:22.378000 139746200525888 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 60946 closing signal SIGTERM
W0620 16:45:22.378000 139746200525888 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 60947 closing signal SIGTERM
W0620 16:45:22.379000 139746200525888 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 60948 closing signal SIGTERM
E0620 16:45:23.722000 139746200525888 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 60943) of binary: /home/vscode/py-env/bin/python3
Traceback (most recent call last):
  File "/home/vscode/py-env/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspaces/torchtune/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/workspaces/torchtune/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/workspaces/torchtune/torchtune/_cli/run.py", line 177, in _run_cmd
    self._run_distributed(args)
  File "/workspaces/torchtune/torchtune/_cli/run.py", line 88, in _run_distributed
    run(args)
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/workspaces/torchtune/recipes/lora_finetune_distributed.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-20_16:45:22
  host      : xxxxxx
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 60943)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

What is the proper way to specify a subset of devices we want to use ?

**Comment by winglian** [comment]
try `CUDA_VISIBLE_DEVICES=...` (plural)

**Comment by lulmer** [comment]
Hi @winglian, Thank you for your answer.
It made me feel stupid at the beginning have to say.
What is worrying is that I still get the same error even with :
```shell
CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 tune run --nproc_per_node 6 lora_finetune_distributed --config llama3/8B_lora.yaml
```

Worth mentioning I am able to train on a single gpu.

**Comment by joecummings** [comment]
Hey @lulmer - couple more questions to help pin down this error and get you training!

1. What type of machines are you using? 
2. What is the output of `echo $NCCL_SOCKET_IFNAME`?
3. What version of PyTorch are you using? `import torch; torch.__version__`
4. What version of CUDA are you using? `nvidia-smi`

All of this will help me further debug where things might be going wrong.

**Comment by lulmer** [comment]
Hey @joecummings, just before reading your message I solved my problem. 
It was an issue with `$NCCL_SOCKET_IFNAME` that was set to `eth0` while the machine I am using only have `lo` as an interface. 

A quick `ifconfig` to get the interface name right and  and setting `export NCCL_SOCKET_IFNAME=lo` prior to launching the training solved my problem.
