### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by epollwait** [pytorch/torchtune#1202]
environment : ubuntu 24.04.   A100 80G *2
tune run --nproc_per_node 2 full_finetune_distributed --config llama3-8B.yaml

pytorch&&torchtune   2.3.1+cu121

[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 607, in <module>
[rank1]:     sys.exit(recipe_main())
[rank1]:              ^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torchtune/config/_parse.py", line 50, in wrapper
[rank1]:     sys.exit(recipe_main(conf))
[rank1]:              ^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 602, in recipe_main
[rank1]:     recipe.train()
[rank1]:   File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 529, in train
[rank1]:     loss.backward()
[rank1]:   File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torch/_tensor.py", line 525, in backward
[rank1]:     torch.autograd.backward(
[rank1]:   File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torch/autograd/__init__.py", line 267, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

W0720 09:36:51.273000 136554030020416 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4273 closing signal SIGTERM
E0720 09:36:52.138000 136554030020416 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 4274) of binary: /home/ubuntu/miniconda3/envs/torchtune/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/torchtune/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torchtune/_cli/run.py", line 177, in _run_cmd
    self._run_distributed(args)
  File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torchtune/_cli/run.py", line 88, in _run_distributed
    run(args)
  File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/ubuntu/miniconda3/envs/torchtune/lib/python3.12/site-packages/recipes/full_finetune_distributed.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4274)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by epollwait** [comment]
I think it's out of memory, it's weird, I can train the model with batch size 6 in single device.
but I can't make it with batch size 3 in 2-gpu device

**Comment by pbontrager** [comment]
Can you give me a command/minimal script for reproducing this? I doubt that the issue is related to batchsize, it seems to randomly plague people depending on their exact pytorch + cuda setup [reference](https://github.com/pytorch/pytorch/issues/21819)

**Comment by gordicaleksa** [comment]
Hitting the same issue, would be cool to get some recommendations for version matching or an official docker image

**Comment by gordicaleksa** [comment]
Solved by downgrading my CUDA version from `2.5.1+cu121` to `2.5.1+cu118`.

I'm installing from source, steps in case it helps someone:
* Clone the torchtune repo `git clone https://github.com/pytorch/torchtune`
* Run `conda create --name ttune python=3.11`
* Run `conda activate ttune`
* Follow https://pytorch.org/get-started/locally/ and run `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
* Run `pip install torchao`
* Navigate to root dir and run `pip install -e .`

That's what worked for me.

**Comment by felipemello1** [comment]
@gordicaleksa, 118 should be fine, but you could try it with cu124 for a more recent one. You can also try pytorch nightlies (2.6 dev). Just run `pip list` to make sure that it was updated.

```
pip install --pre --upgrade torch torchvision torchao --index-url https://download.pytorch.org/whl/nightly/cu124
```
