### ISSUE TITLE
Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data

### ISSUE THREAD

**Issue by Vattikondadheeraj** [pytorch/torchtune#1493]
Hey,

I have seen the previous issues. Based on that I tracked down the approximate lane where the pipeline is struck which is the setup function where it failed to load the model. The training is not yet started. I have attached the corresponding code and log files. 

Hardware Information :- 2 - A100 Gpu

```
def recipe_main(cfg: DictConfig) -> None:
    """
    Entry point for the recipe.

    Configurable parameters are read in the following order:
        - Parameters specified in config (see available configs through ``tune ls``)
        - Overwritten by arguments from the command-line
    """
    if not utils.is_distributed():
        raise RuntimeError(
            "Distributed finetune recipe should be run via a distributed launcher."
            "If using tune CLI, please specify --nnodes 1 and --nproc_per_node [num_gpus]"
        )
    os.environ["TORCH_NCCL_AVOID_RECORD_STREAMS"] = "1" 
    init_process_group(backend="gloo" if cfg.device == "cpu" else "nccl")

    config.log_config(recipe_name="LoRAFinetuneRecipeDistributed", cfg=cfg)
    print("hhihihiihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi1")   

    recipe = LoRAFinetuneRecipeDistributed(cfg, cots, variables_data)
    print("hhihihiihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi22222")   
    recipe.setup(cfg=cfg)
    print("hhihihiihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi33333") 
    recipe.train()
    print("hhihihiihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi44444") 
    recipe.cleanup()
```

```
def setup(self, cfg: DictConfig) -> None:
        """
        Setup the recipe state. This includes recipe state (if resume_from_checkpoint is True),
        model, tokenizer, loss, optimizer, learning rate scheduler, sampler, and dataloader.
        """
        
        print("byebyeybeybeybeyebbeye1111111")
        if self._is_rank_zero:
            self._metric_logger = config.instantiate(cfg.metric_logger)

            # log config with parameter override
            self._metric_logger.log_config(cfg)
        print("byebyeybeybeybeyebbeye222222222")

        checkpoint_dict = self.load_checkpoint(cfg_checkpointer=cfg.checkpointer)
        print("byebyeybeybeybeyebbeye333333333")

        self._model_compile = cfg.get("compile", False)
        self._model = self._setup_model(
            cfg_model=cfg.model,
            enable_activation_checkpointing=cfg.enable_activation_checkpointing,
            base_model_state_dict=checkpoint_dict[training.MODEL_KEY],
            lora_weights_state_dict=(
                checkpoint_dict[training.ADAPTER_KEY]
                if self._resume_from_checkpoint
                else None
            ),
        )
        
        print("byebyeybeybeybeyebbeye444444444444")
        self._tokenizer = config.instantiate(cfg.tokenizer)

        self._optimizer = self._setup_optimizer(
            cfg_optimizer=cfg.optimizer,
            opt_state_dict=checkpoint_dict[training.OPT_KEY]
            if self._resume_from_checkpoint
            else None,
        )

        # initialize loss
        self._loss_fn = config.instantiate(cfg.loss)
        backend = os.environ.get("TORCH_COMPILE_BACKEND", "inductor")
        if self._loss_fn.__class__.__name__ == "CEWithChunkedOutputLoss":
            # set num_output_chunks for model
            self._model.set_num_output_chunks(self._loss_fn.num_output_chunks)
            if self._model_compile:
                log.info("Compiling loss with torch.compile...")
                # For CEWithChunkedOutputLoss, if we compile the entire class
                # we lose the benefits from the chunked loss.
                # Therefore, we only compile the cross entropy function + upcasting
                self._loss_fn.compute_cross_entropy = torch.compile(
                    self._loss_fn.compute_cross_entropy, backend=backend
                )
        else:
            if self._model_compile:
                log.info("Compiling loss with torch.compile...")
                self._loss_fn = torch.compile(self._loss_fn, backend=backend)
        log.info("Loss is initialized.")

        # sampler and dataloader depend on the tokenizer and loss_fn and should be
        # setup after all of these are setup
        # self._sampler, self._dataloader = self._setup_data(
        #     cfg_dataset=cfg.dataset,
        #     shuffle=cfg.shuffle,
        #     batch_size=cfg.batch_size,
        # )
        
        print("byebyeybeybeybeyebbeye5555555555555")
        
        self._sampler, self._dataloader= self.setup_data_(
        self.cots,
        self.variable_data,
        self._tokenizer,
        cfg.shuffle,
        cfg.batch_size)
        
        
        print("byebyeybeybeybeyebbeye66666666666666")

        # Finally update the recipe state which can only be correctly set after all of the
        # other components have been initialized and updated.

        # Number of training steps in each epoch depends on the number of batches produced
        # by the dataloader and the max_steps_per_epoch param set by the user and is used
        # for logging and tracking training state. This should be computed after the dataloader
        # has been setup
        self._steps_per_epoch = (
            len(self._dataloader) // self._gradient_accumulation_steps
        )
        if (
            self.max_steps_per_epoch is not None
            and self.max_steps_per_epoch < self._steps_per_epoch
        ):
            self._steps_per_epoch = self.max_steps_per_epoch
        self.global_step = self.epochs_run * self._steps_per_epoch

        # Learning rate scheduler can only be set up after number of steps
        # has been computed
        self._lr_scheduler = self._setup_lr_scheduler(
            cfg_lr_scheduler=cfg.lr_scheduler,
            num_training_steps=self.total_epochs * self._steps_per_epoch,
            last_epoch=self.global_step - 1,
        )

        # Set up profiler, returns DummyProfiler (nullcontext object with no-op `step` method)
        # if cfg is missing profiler key or if `cfg.profiler.enabled = False`
        self._profiler = self._setup_profiler(cfg.get(PROFILER_KEY, None))

        # Used to ignore labels for loss computation
        self.ignore_labels_cache = torch.full(
            (cfg.batch_size, 1), self._loss_fn.ignore_index, device=self._device
        )
```

This is my Log File for more information

```
INFO:torchtune.utils.logging:Running LoRAFinetuneRecipeDistributed with resolved config:

batch_size: 2
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /home/vdhee/scratch/LLMcode/Train/models/
  checkpoint_files:
  - model-00001-of-00004.safetensors
  - model-00002-of-00004.safetensors
  - model-00003-of-00004.safetensors
  - model-00004-of-00004.safetensors
  model_type: LLAMA3
  output_dir: /home/vdhee/scratch/LLMcode/Train/models/output
  recipe_checkpoint: null
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
device: cuda
dtype: bf16
enable_activation_checkpointing: false
epochs: 1
gradient_accumulation_steps: 32
log_every_n_steps: 1
log_peak_memory_stats: false
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
max_steps_per_epoch: null
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: /home/vdhee/scratch/LLMcode/Train/Log_FIle
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b
  apply_lora_to_mlp: false
  apply_lora_to_output: false
  lora_alpha: 16
  lora_attn_modules:
  - q_proj
  - v_proj
  lora_rank: 8
optimizer:
  _component_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: 0.01
output_dir: /home/vdhee/scratch/LLMcode/Train/Log_FIle
resume_from_checkpoint: false
save_adapter_weights_only: false
seed: null
shuffle: true
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  max_seq_len: null
  path: /home/vdhee/scratch/LLMcode/Train/models/original/tokenizer.model

hhihihiihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi1
DEBUG:torchtune.utils.logging:Setting manual seed to local seed 3816754976. Local seed is seed + rank = 3816754976 + 0
hhihihiihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi22222
byebyeybeybeybeyebbeye1111111
hhihihiihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi22222
byebyeybeybeybeyebbeye1111111
byebyeybeybeybeyebbeye222222222
Writing logs to /home/vdhee/scratch/LLMcode/Train/Log_FIle/log_1725478018.txt
byebyeybeybeybeyebbeye222222222
byebyeybeybeybeyebbeye333333333
INFO:torchtune.utils.logging:FSDP is enabled. Instantiating Model on CPU for Rank 0 ...
byebyeybeybeybeyebbeye333333333
INFO:torchtune.utils.logging:Model instantiation took 15.90 secs


[rank1]:[E ProcessGroupNCCL.cpp:523] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=BROADCAST, NumelIn=32768, NumelOut=32768, Timeout(ms)=600000) ran for 600852 milliseconds before timing out.
[rank1]:[E ProcessGroupNCCL.cpp:537] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E ProcessGroupNCCL.cpp:543] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E ProcessGroupNCCL.cpp:1182] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=BROADCAST, NumelIn=32768, NumelOut=32768, Timeout(ms)=600000) ran for 600852 milliseconds before timing out.
Exception raised from checkTimeout at /home/coulombc/wheels_builder/tmp.2192/python-3.11/torch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xa9 (0x150cf6d3f4b9 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xf120e1 (0x150cf7d2f0e1 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e0 (0x150cf7d07de0 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x173 (0x150cf7d082a3 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10b (0x150cf7d08adb in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xdc0ef (0x150d37c630ef in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6)
frame #6: <unknown function> + 0x84a9d (0x150d389b8a9d in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib64/libc.so.6)
frame #7: __clone + 0x40 (0x150d38a38fc0 in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib64/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2, OpType=BROADCAST, NumelIn=32768, NumelOut=32768, Timeout(ms)=600000) ran for 600852 milliseconds before timing out.
Exception raised from checkTimeout at /home/coulombc/wheels_builder/tmp.2192/python-3.11/torch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:525 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xa9 (0x150cf6d3f4b9 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xf120e1 (0x150cf7d2f0e1 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1e0 (0x150cf7d07de0 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x173 (0x150cf7d082a3 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10b (0x150cf7d08adb in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xdc0ef (0x150d37c630ef in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6)
frame #6: <unknown function> + 0x84a9d (0x150d389b8a9d in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib64/libc.so.6)
frame #7: __clone + 0x40 (0x150d38a38fc0 in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib64/libc.so.6)

Exception raised from ncclCommWatchdog at /home/coulombc/wheels_builder/tmp.2192/python-3.11/torch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1186 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xa9 (0x150cf6d3f4b9 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xf120e1 (0x150cf7d2f0e1 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xc6da14 (0x150cf7a8aa14 in /home/vdhee/.local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xdc0ef (0x150d37c630ef in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6)
frame #4: <unknown function> + 0x84a9d (0x150d389b8a9d in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib64/libc.so.6)
frame #5: __clone + 0x40 (0x150d38a38fc0 in /cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib64/libc.so.6)

[2024-09-04 15:37:08,067] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1153515 closing signal SIGTERM
[2024-09-04 15:37:08,682] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 1 (pid: 1153516) of binary: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/bin/python
Traceback (most recent call last):
  File "/home/vdhee/.local/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lustre07/scratch/vdhee/LLMcode/Train/torchtune/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/lustre07/scratch/vdhee/LLMcode/Train/torchtune/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/lustre07/scratch/vdhee/LLMcode/Train/torchtune/torchtune/_cli/run.py", line 177, in _run_cmd
    self._run_distributed(args)
  File "/lustre07/scratch/vdhee/LLMcode/Train/torchtune/torchtune/_cli/run.py", line 88, in _run_distributed
    run(args)
  File "/home/vdhee/.local/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/vdhee/.local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vdhee/.local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/lustre07/scratch/vdhee/LLMcode/Train/torchtune/recipes/lora_finetune_distributed.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-04_15:37:08
  host      : ng11105.narval.calcul.quebec
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 1153516)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 1153516
============================================================
```

**Comment by ebsmothers** [comment]
@Vattikondadheeraj based on your logs I guess it's happening somewhere in [here](https://github.com/pytorch/torchtune/blob/f1fbe1ac6c9a1def639465f8c3b628b9fe5b9b4b/recipes/lora_finetune_distributed.py#L411-L488). Re @felipemello1's suggestion (2) we do already have a barrier at the end of `_setup_model` (it's possible this is where the timeout is occurring). So it may be that there is something going wrong with either the loading of your state dict or the FSDP wrapping. In addition to Felipe's suggestion to run with `NCCL_DEBUG=INFO`, a couple other things I would suggest trying:

(1) run the single-device recipe if you haven't already to confirm it's truly a distributed issue
(2) as a sanity check you can try setting the sharding strategy [here](https://github.com/pytorch/torchtune/blob/f1fbe1ac6c9a1def639465f8c3b628b9fe5b9b4b/recipes/lora_finetune_distributed.py#L458) to NO_SHARD ([ref](https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.ShardingStrategy)). This will fully replicate the model across both ranks in case there is something wrong with how the model is being sharded.
(3) try the FSDP2 recipe [here](https://github.com/pytorch/torchtune/blob/f1fbe1ac6c9a1def639465f8c3b628b9fe5b9b4b/recipes/dev/lora_finetune_fsdp2.py#L4) (we are migrating our lora_finetune_distributed recipe onto this very soon and there should be less tricky interactions with stuff like meta device)

Separately if you can share the version of PyTorch you're running on, the command you used, etc. that would also be helpful

**Comment by Vattikondadheeraj** [comment]
@felipemello1 , sorry for the late response. I have tried everything that you mentioned and it works but the problem is sometimes it takes a lots of time i guess around 20 to 30min even with the single gpu setting. Is there anything I can do to speed up the process?

@ebsmothers, for FSDP2 which torch version should I use? and even of other packages. Can you add requirements.txt file for FSDP2?

**Comment by ebsmothers** [comment]
@Vattikondadheeraj for the best performance you can use PyTorch nightlies, but even on stable PyTorch 2.4 you should have no problems running FSDP2. There’s no change necessary from your side, if you install the latest stable version of torchtune (which we just released this morning) and run any of our distributed recipes you will now be using FSDP2.

But if it’s taking 20-30 minutes even on a single GPU, seems like something else is happening that’s not related to distributed anyways.
