### ISSUE TITLE
CUDA out of memory for alpaca generate

### ISSUE THREAD

**Issue by yechenzhi** [pytorch/torchtune#612]
I only have two 24g 4090s, when I run 'tune alpaca_generate --config alpaca_generate' or 'tune --nnodes 1 --nproc_per_node 2 alpaca_generate --config alpaca_generate',  I got CUDA OOM error, I checked the config, the max batch size is already set to 1, and the model is 'torchtune.models.llama2.llama2_7b'.

Any suggestions for poor men like me?

**Comment by kartikayk** [comment]
Thank you for filing this issue @yechenzhi! The generation script is currently under heavy development since both memory and perf isn't great. I'll have an update PR ready for this some time tomorrow which should hopefully address this issue. I'll comment on here with the PR once this is ready.

**Comment by ebsmothers** [comment]
Hi @yechenzhi, thanks for the issue. For the `nproc_per_node 2` case, actually we do not support it yet 😅 . You can see [here](https://github.com/pytorch/torchtune/blob/8245523701e006ed6330633c719d06f6255e1260/recipes/alpaca_generate.py#L49-L52) that we are just loading the model onto the current device. Additionally, I believe we are loading the model in fp32, so on a single device the model params will take up ~27GB, which is too much for your machine. 

One workaround is to initialize the model in bf16. If you've git cloned and installed in editable mode, you can just directly modify the file `recipes/alpaca_generate.py`; if not you can use `tune cp` to copy the file and modify it. 

Then you can use the `set_default_dtype` utility when initializing your model (similar to what's done in the finetuning recipe [here](https://github.com/pytorch/torchtune/blob/8245523701e006ed6330633c719d06f6255e1260/recipes/full_finetune_single_device.py#L203-L204)). Just modify the code from the first pointer I shared by adding `utils.set_default_dtype(torch.bfloat16)` to the `with` statement. I ran this on my machine and the peak memory I see is 16GB, so I hope it'll resolve your OOM. Note that the actual generation code assumes you're running in fp32 as well, so you may need to add the same `set_default_dtype` call [here](https://github.com/pytorch/torchtune/blob/8245523701e006ed6330633c719d06f6255e1260/recipes/alpaca_generate.py#L60) to get all your tensors dtypes to line up.

In general reducing the precision will have an impact on the quality of the generations, but in this case the model weights are likely already in bf16 so you shouldn't see any negative impact.

You might ask why our generate recipe is missing some of the features we have in our other recipes. As @kartikayk mentioned, we are hoping to make some improvements on this front soon, so please stay tuned 😃 .

**Comment by yechenzhi** [comment]
Thanks! OOM problem solved! However, my generations do not seem right, for example:

> ex1:
> ### Instruction:
> Answer the question.
> 
> ### Input:
> What is some cool music from the 1920s?
> 
> ### Response:
> 
> Artist:    ________________
> 
> Album:     _________________
> 
> Song:      _________________
> 
> $\braries{21324 - misconduct - Dismissed.dat.gz}.subset(P2, select = -IncidentEndDate).d
> 
> ex2:
> ### Instruction:
> Answer the question.
> 
> ### Input:
> Why pytorch is so popular?
> 
> ### Response:
> Pytorch is easier to learn than numpy since it is built on torch.nn.
> 
> #### ___________________________________________________________________________
> 
> ##### Hint:
> 
> * *This is called topic spotlighting*
> 
> Pytorihc isn't that popular. It isn't that well known, is it

Is this normal? My model_checkpoint is /tmp/llama2/consolidated.00.pth, and I added 'meta_to_tune(native_state_dict)' [here](https://github.com/pytorch/torchtune/blob/5cbc1967b4ed59b658044be44215ba6efd540271/recipes/alpaca_generate.py#L55).

**Comment by kartikayk** [comment]
What are the generation params you're using? You probably want to set top_k to something like 200 and usually 0.8 for the temperature.

The checkpoint setup seems fine to me. But I'd recommend calling ```load_state_dict``` with ```strict=True``` (which is the default). This will ensure an error is raised if the keys don't line up - which they should if you're using ```meta_to_tune```.

**Comment by yechenzhi** [comment]
Thanks! I set top_k to 200 and temperature to 0.8, the generations now seem all right!
